---
image: metalstack/builder:latest

binary:
  script:
    - make platforms
    - strip bin/cloudctl-linux-amd64
    - bin/cloudctl-linux-amd64 update dump bin/cloudctl-linux-amd64 > version-linux-amd64.json
    - bin/cloudctl-linux-amd64 update dump bin/cloudctl-windows-amd64 > version-windows-amd64.json
    - bin/cloudctl-linux-amd64 update dump bin/cloudctl-darwin-amd64 > version-darwin-amd64.json
  only:
    - master

binary-with-slug:
  script:
    - make platforms
    - strip bin/cloudctl-linux-amd64
    - bin/cloudctl-linux-amd64 update dump bin/cloudctl-linux-amd64 > version-linux-amd64.json
    - bin/cloudctl-linux-amd64 update dump bin/cloudctl-windows-amd64 > version-windows-amd64.json
    - bin/cloudctl-linux-amd64 update dump bin/cloudctl-darwin-amd64 > version-darwin-amd64.json
  only:
    - tags

mergerequest:
  script:
    - make all
  only:
    - merge_requests
