package pkg

import (
	"fmt"
	"strings"

	gardencorev1alpha1 "github.com/gardener/gardener/pkg/apis/core/v1alpha1"
	"k8s.io/apimachinery/pkg/util/intstr"

	gardenv1beta1 "github.com/gardener/gardener/pkg/apis/garden/v1beta1"

	corev1 "k8s.io/api/core/v1"

	"git.f-i-ts.de/cloud-native/cloudctl/pkg/api"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CreateShoot create a shoot for a project
func (g *Gardener) CreateShoot(scr *api.ShootCreateRequest) (*gardenv1beta1.Shoot, error) {
	p, err := g.CreateProject(scr.Owner)
	if err != nil {
		return nil, err
	}
	fmt.Printf("Project:%s Namespace:%s UID: %s created\n", p.GetName(), p.GetNamespace(), p.GetUID())

	sb, err := g.CreateSecretBinding(p)
	if err != nil {
		return nil, err
	}
	fmt.Printf("SecretBinding:%s created\n", sb.GetName())

	project, err := g.client.GardenV1beta1().Projects().Get(p.GetName(), metav1.GetOptions{})
	if err != nil {
		return nil, err
	}
	var createdBy string
	if project.Spec.CreatedBy != nil {
		createdBy = project.Spec.CreatedBy.Name
	}

	maxSurge := intstr.FromInt(scr.Workers[0].MaxSurge)
	maxUnavailable := intstr.FromInt(scr.Workers[0].MaxUnavailable)

	nodesCIDR := gardencorev1alpha1.CIDR("")
	podsCIDR := gardencorev1alpha1.CIDR("")
	servicesCIDR := gardencorev1alpha1.CIDR("")
	// FIXME helper method
	region := strings.Split(scr.Zones[0], "-")[0]
	shoot := &gardenv1beta1.Shoot{
		ObjectMeta: metav1.ObjectMeta{
			Name: project.Name,
			Annotations: map[string]string{
				"garden.sapcloud.io/createdBy": createdBy,
				"garden.sapcloud.io/purpose":   *scr.Purpose,
				"cluster.metal-pod.io/project": project.Name,
			},
			Namespace: *project.Spec.Namespace,
		},
		Spec: gardenv1beta1.ShootSpec{
			Addons: &gardenv1beta1.Addons{
				KubernetesDashboard: &gardenv1beta1.KubernetesDashboard{
					Addon: gardenv1beta1.Addon{Enabled: false},
				},
				NginxIngress: &gardenv1beta1.NginxIngress{
					Addon: gardenv1beta1.Addon{Enabled: true},
				},
			},
			Cloud: gardenv1beta1.Cloud{
				Profile: "metal",
				Region:  region,
				SecretBindingRef: corev1.LocalObjectReference{
					Name: sb.Name,
				},
				Metal: &gardenv1beta1.MetalCloud{
					LoadBalancerProvider: scr.LoadBalancerProvider,
					MachineImage: &gardenv1beta1.MachineImage{
						Name:    scr.MachineImage.Name,
						Version: scr.MachineImage.Version,
					},
					FirewallImage: scr.FirewallImage,
					FirewallSize:  scr.FirewallSize,
					Networks: gardenv1beta1.MetalNetworks{
						K8SNetworks: gardencorev1alpha1.K8SNetworks{
							Nodes:    &nodesCIDR,
							Pods:     &podsCIDR,
							Services: &servicesCIDR,
						},
						Additional: scr.Networks,
					},
					Workers: []gardenv1beta1.MetalWorker{
						gardenv1beta1.MetalWorker{
							Worker: gardenv1beta1.Worker{
								Name:           scr.Workers[0].Name,
								MachineType:    scr.Workers[0].MachineType,
								AutoScalerMin:  scr.Workers[0].AutoScalerMin,
								AutoScalerMax:  scr.Workers[0].AutoScalerMax,
								MaxSurge:       &maxSurge,
								MaxUnavailable: &maxUnavailable,
							},
							VolumeType: scr.Workers[0].VolumeType,
							VolumeSize: scr.Workers[0].VolumeSize,
						},
					},
					Zones: scr.Zones,
				},
			},
			Kubernetes: gardenv1beta1.Kubernetes{
				AllowPrivilegedContainers: &scr.Kubernetes.AllowPrivilegedContainers,
				Version:                   scr.Kubernetes.Version,
			},
			Maintenance: &gardenv1beta1.Maintenance{
				AutoUpdate: &gardenv1beta1.MaintenanceAutoUpdate{
					KubernetesVersion: scr.Maintenance.AutoUpdate.KubernetesVersion,
					// MachineImageVersion: &autoUpdate,
				},
				TimeWindow: &gardenv1beta1.MaintenanceTimeWindow{
					Begin: scr.Maintenance.TimeWindow.Begin,
					End:   scr.Maintenance.TimeWindow.End,
				},
			},
		},
	}

	return g.client.GardenV1beta1().Shoots(*project.Spec.Namespace).Create(shoot)
	// 	apiVersion: garden.sapcloud.io/v1beta1
	// kind: Shoot
	// metadata:
	//     annotations:
	//         garden.sapcloud.io/createdBy: heinz.schenk@f-i-ts.de
	//         garden.sapcloud.io/purpose: production # will prevent a default hibernation schedule...
	//         cluster.metal-pod.io/project: ice-deployment
	//     name: <auto-generated-by-gardener> # maximum 10 characters
	//     namespace: garden-<cluster-id>
	// spec:
	//     addons:
	//         kubernetes-dashboard:
	//             enabled: false
	//         nginx-ingress:
	//             enabled: false # would deploy one load balancer type service, which ip address we do not want to give away just like that... it's also unclear from which network it should grab an ip
	//     cloud:
	//         metal:
	//             tenant: hlb
	//             firewallImage: firewall-1
	//             firewallSize: c1-xlarge-x86
	//             loadbalancer:
	//                 enabled: true
	//                 networks:
	//                 - count: 1 # one for vpn-shoot is required from us, it is important that vpn connection gets established otherwise the cluster is not "healthy" because api server can't reach the workers
	//                   name: internet-nbg-w8101
	//                 loadBalancerProvider: metallb
	//             machineImage:
	//                 name: metal
	//                 version: ubuntu-19.04
	//             networks:
	//                 additional:
	//                 - <external-networks>
	//                 nodes: 10.250.0.0/16
	//                 pods: 10.242.0.0/16
	//                 services: 10.243.0.0/16
	//             workers:
	//             -   autoScalerMax: 1
	//                 autoScalerMin: 1
	//                 machineType: c1-xlarge-x86
	//                 maxSurge: 1
	//                 maxUnavailable: 0
	//                 name: worker-x1a35
	//                 volumeSize: 50Gi # not interesting for us as it is bound to the machine type
	//                 volumeType: storage_1 # not interesting for us as it is bound to the machine type
	//             zones:
	//             - nbg-w8101
	//             profile: metal
	//             region: nbg
	//         secretBindingRef:
	//             name: garden-<cluster-id>
	//             seed: garden-<cluster-id>
	//     kubernetes:
	//         allowPrivilegedContainers: true
	//         version: 1.14.3
	//     maintenance:
	//         autoUpdate:
	//         kubernetesVersion: true
	//         timeWindow:
	//         begin: 230000+0000
	//         end: 000000+0000

}
