---
name: Docker Build Action
on:
  pull_request:
    branches:
      - master
  release:
    types:
      - published
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --build-tags integration -p bugs -p unused --timeout=3m

      - name: Build
        run: |
          make extract-binaries

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            result/cloudctl-*
        if: ${{ github.event_name == 'release' }}
