name: master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: -p bugs -p unused --timeout=3m
      - name: Build
        uses: metal-stack/action-docker-make@master
        with:
          args: >
            --no-cache
            --no-push
            --build-only cloudctl-master
            -x rule2,rule3
            --summary
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
